

services:

    crossKnowledge.datatable.twig_extension:
        class: CrossKnowledge\DataTableBundle\Twig\DataTableExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }

    crossknowledge_datatable.registry:
        class: CrossKnowledge\DataTableBundle\DataTable\DataTableRegistry

    crossknowledge_datatable.default_formatter:
        class: CrossKnowledge\DataTableBundle\DataTable\Formatter\DefaultFormatter

    crossknowledge_datatable.classic_table:
        abstract: true
        arguments:
            - @form.factory
            - @security.authorization_checker
            - @router
            - @crossknowledge_datatable.default_formatter

    crossknowledge_datatable.default_renderer:
        alias: crossknowledge_datatable.twig_renderer

    crossknowledge_datatable.json_renderer:
        class: CrossKnowledge\DataTableBundle\DataTable\Renderer\JsonRenderer

    crossknowledge_datatable.twig_renderer:
        class: CrossKnowledge\DataTableBundle\DataTable\Renderer\TwigRenderer
        arguments: [@templating]
        