language: php

php:
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

